import Product from "@Models/Product/Product";
import Price from "@Models/Product/Price";

const pricetrial : Price = {
    id: 1,
    amount: 1050,
    date: "12-05-2023"  
}

export function getProducts() {

    let data: Product[] = [{
        id: 1,
        name: "Hamburguesa simple con queso",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: false,
        productCategory: "burgers",
        price: pricetrial,
        image: "burger.jpg",
    },
    {
        id: 2,
        name: "Pizza napolitana 8 porc.",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "pizzas",
        price: pricetrial,
        image: "pizza.jpg",
    },
    {
        id: 3,
        name: "Papas chicas",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "fries",
        price: pricetrial,
        image: "french-fries.jpg",
    },
    {
        id: 4,
        name: "Coca-Cola 500ml.",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: false,
        productCategory: "drinks",
        price: pricetrial,
        image: "coca-cola.jpg",
    },
    {
        id: 5,
        name: "Hamburguesa simple con queso + papas chicas",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "combos",
        price: pricetrial,
        image: "burger-with-fries.jpg",
    },
    {
        id: 6,
        name: "Hamburguesa simple con queso veggie",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "burgers",
        price: pricetrial,
        image: "burger.jpg",
    },{
        id: 7,
        name: "Hamburguesa doble con queso",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "burgers",
        price: pricetrial,
        image: "burger.jpg",
    },
    {
        id: 8,
        name: "Hamburguesa simple con queso veggie",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "burgers",
        price: pricetrial,
        image: "burger.jpg",
    },
    {
        id: 9,
        name: "Hamburguesa doble con queso",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "burgers",
        price: pricetrial,
        image: "burger.jpg",
    },
    {
        id: 10,
        name: "2 Hamburguesa simple con queso + 2 papas chicas",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "combos",
        price: pricetrial,
        image: "burger-with-fries.jpg",
    },
    {
        id: 11,
        name: "3 Hamburguesa simple con queso + 3 papas chicas",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: false,
        productCategory: "combos",
        price: pricetrial,
        image: "burger-with-fries.jpg",
    },
    {
        id: 12,
        name: "4 Hamburguesa simple con queso + 4 papas chicas",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "combos",
        price: pricetrial,
        image: "burger-with-fries.jpg",
    },
    {
        id: 13,
        name: "Coca-Cola Cero 1l.",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "drinks",
        price: pricetrial,
        image: "coca-cola.jpg",
    },
    {
        id: 14,
        name: "Coca-Cola 1l.",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "drinks",
        price: pricetrial,
        image: "coca-cola.jpg",
    },
    {
        id: 15,
        name: "Coca-Cola Cero 500ml.",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "drinks",
        price: pricetrial,
        image: "coca-cola.jpg",
    },
    {
        id: 16,
        name: "Papas medianas",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "fries",
        price: pricetrial,
        image: "french-fries.jpg",
    },
    {
        id:17,
        name: "Papas grandes",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "fries",
        price: pricetrial,
        image: "french-fries.jpg",
    },
    {
        id: 18,
        name: "Pizza muzzarella 8 porc.",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna. Phasellus aliquet tempor lorem, ac dapibus massa vestibulum eget. Aenean sed egestas leo, ut tempus dolor. ",
        shortDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis egestas magna.",
        available: true,
        productCategory: "pizzas",
        price: pricetrial,
        image: "pizza.jpg",
    }];
    return data;
}